context.modules = [
{
    name = libpipewire-module-rtp-sink
    args = {
        local.ifname = "eth0"
        destination.ip = "192.168.1.50"
        destination.port = 5004
        format = "S16"
        rate = 48000
        channels = 2
    }
}
]
