 context.modules = [
 {   name = libpipewire-module-rtp-sink
     args = {
         local.ifname = "br0"
         source.ip = "0.0.0.0"
         destination.ip = "224.0.0.56"
         destination.port = 44444
         net.mtu = 1280
         net.ttl = 1
         net.loop = false
         sess.min-ptime = 2
         sess.max-ptime = 20
         sess.name = "PipeWire RTP hifi"
         sess.media = "audio"
         audio.format = "S16BE"
         audio.rate = 48000
         audio.channels = 2
         audio.position = [ FL FR ]
         stream.props = {
             node.name = "rtp-sink"
         }
     }
}
]
