context.modules = [
{   name = libpipewire-module-rtp-source
    args = {
        local.ifname = end0
        source.ip = 224.0.0.56
        source.port = 44444
        sess.latency.msec = 100
        #sess.ignore-ssrc = false
        #node.always-process = false
        sess.media = "audio"
        sess.name = "PipeWire RTP hifi"
        audio.format = "S16BE"
        audio.rate = 48000
        audio.channels = 2
        audio.position = [ FL FR ]
        stream.props = {
           media.class = "Audio/Source"
           node.name = "rtp-source"
        }
    }
}
]
