context.modules = [
{
    name = libpipewire-module-rtp-source
    args = {
        local.ifname = "eth0"
        local.port = 5004
        format = "S16"
        rate = 48000
        channels = 2
    }
}
]
